(function($,Voonto){"use strict";var prospectGigya={privacyPolicy:"20180525"};var tagManagerMode="widget";var widgetList="";var widgetTypeList=[];var slotList=[];var auth=!1;var ajaxComplete;var mainEventListener=$("body");var currentRequests=[];var ssoGroupCode="1100";var env="PRO";var range=document.createRange(),snippets=document.getElementsByClassName("widget-prospect");var protocol=location.protocol;var urlProspectPublic=protocol+"//newsletters.vocento.com";var urlProspectVoccore=protocol+"//voccore.larioja.com";function eventLoad(){mainEventListener.on("vocento.vocuser:accounts:onDataReady",function(event){if(env!=="PRO"){console.log("onDataReady");console.log(event)}
auth=!0;var widgetProspect=$(".widget-prospect");if(typeof event.gigya_event.profile.email!=="undefined"){widgetProspect.find(".prospectEmail").val(event.gigya_event.profile.email).prop("readonly",!0)}
if(typeof event.gigya_event.profile.firstName!=="undefined"){widgetProspect.find(".prospectFirstname").val(event.gigya_event.profile.firstName).prop("readonly",!0)}
if(typeof event.gigya_event.profile.lastName!=="undefined"){widgetProspect.find(".prospectLastname").val(event.gigya_event.profile.lastName).prop("readonly",!0)}
if(typeof event.gigya_event.profile.zip!=="undefined"){widgetProspect.find(".prospectZip").val(event.gigya_event.profile.zip).prop("readonly",!0)}
if(typeof event.gigya_event.profile.birthDay!=="undefined"){widgetProspect.find(".prospectBirthday").val(event.gigya_event.profile.birthDay).prop("readonly",!0)}
if(typeof event.gigya_event.profile.birthMonth!=="undefined"){widgetProspect.find(".prospectBirthmonth").val(event.gigya_event.profile.birthMonth).prop("readonly",!0)}
if(typeof event.gigya_event.profile.birthYear!=="undefined"){widgetProspect.find(".prospectBirthyear").val(event.gigya_event.profile.birthYear).prop("readonly",!0)}});mainEventListener.on("vocento.vocuser:accounts:onDataNoReady",function(e){if(env!=="PRO"){console.log("onDataNoReady");console.log(e)}});mainEventListener.on("vocento.vocuser:prospect:getWidgetList",function(event,eventData){eventData.widgetList=widgetList});mainEventListener.on("vocento.vocuser:prospect:getTagManagerMode",function(event,eventData){eventData.tagManagerMode=tagManagerMode});mainEventListener.on("vocento.vocuser:prospect:getAjaxComplete",function(event,eventData){eventData.ajaxComplete=ajaxComplete})}
$(document).ready(function(){ajaxComplete=$.Deferred();$(".widget-prospect").keydown(function(event){if(event.keyCode===13){event.preventDefault();return!1}});Voonto.ready.then(eventLoad);if(ssoGroupCode!=="0100"){var linkCss=document.createElement("link");var fullUrlCss=urlProspectPublic+"/prospect/"+ssoGroupCode+"/css/widget.css/v1";linkCss.setAttribute("href",fullUrlCss);linkCss.setAttribute("type","text/css");linkCss.setAttribute("rel","stylesheet");document.head.appendChild(linkCss)}
var linkPopboxCss=document.createElement("link");var fullUrlPopboxCss=urlProspectPublic+"/prospect/"+ssoGroupCode+"/css/popbox.css";linkPopboxCss.setAttribute("href",fullUrlPopboxCss);linkPopboxCss.setAttribute("type","text/css");linkPopboxCss.setAttribute("rel","stylesheet");document.head.appendChild(linkPopboxCss);var scriptTagManagerService=document.createElement("script");var fullURLTagManagerService=urlProspectPublic+"/prospect/"+ssoGroupCode+"/js/tag-manager.js";scriptTagManagerService.setAttribute("src",fullURLTagManagerService);scriptTagManagerService.setAttribute("type","application/javascript");document.head.appendChild(scriptTagManagerService);for(var i=0;i<snippets.length;i++){slotList[snippets[i].dataset.widgetId]="no slot";if(("widgetSlot" in snippets[i].dataset)){slotList[snippets[i].dataset.widgetId]=snippets[i].dataset.widgetSlot}
replaceWithWidget(snippets[i]);if(ssoGroupCode!=="0100"){getStyle(snippets[i])}}})
function getStyle(snippet){var snippets=[];var widgetId=snippet.dataset.widgetId;var check=snippets.indexOf(widgetId);snippets.push(snippet.dataset.widgetId);if(check===-1){var link=document.createElement("link");link.href=urlProspectPublic+"/prospect/"+ssoGroupCode+"/css/widget.css/"+widgetId;link.setAttribute("type","text/css");link.setAttribute("rel","stylesheet");document.head.appendChild(link)}}
function replaceWithWidget(snippet){var invocation=new XMLHttpRequest(),url=urlProspectVoccore+"/vocuser/v1/prospect/widget/",widgetId=snippet.dataset.widgetId;invocation.open("GET",url+widgetId,!0);invocation.setRequestHeader("Accept","application/vnd.voccore.prospect.v2");listTrackListener(invocation);invocation.onreadystatechange=function(){if(invocation.readyState===4){if(invocation.status===200){var randomId=Math.random().toString(36).substr(2,9);var json=JSON.parse(invocation.responseText);var widget=range.createContextualFragment(json.result.body);widgetTypeList[snippet.dataset.widgetId]=json.result.subscription_type;snippet.dataset.widgetId="wid-"+widgetId;if(!0===json.result.testMode){snippet.dataset.widgetId="wid-dev-"+widgetId}
var form=widget.querySelector("form");var botonSubmit=widget.querySelector(".prospect-submit");var botonSubmitChildren=botonSubmit.children;var botonSubmitModal=widget.querySelector(".btn-success-widget-prospect");var botonCloseModal=widget.querySelector(".close-widget-prospect");var modal=widget.querySelector(".modal-widget-prospect");if(botonSubmit){botonSubmit.dataset.vocVtmId="btnsuscribirse-"+widgetId}
if(botonSubmitModal){botonSubmitModal.dataset.vocVtmId="btnsuscribirse-"+widgetId}
var idWidgetSubmit="widgetSubmit"+randomId;form.addEventListener("submit",doSubscription);form.id=randomId;form.setAttribute("autocomplete","off");modal.id="modal-widget-prospect"+randomId;modal.setAttribute("data-popbox-id","modal"+randomId);botonSubmitModal.setAttribute("form",randomId);botonSubmitModal.setAttribute("data-popbox-close","modal"+randomId);botonSubmitModal.setAttribute("onclick","document.getElementById(\""+idWidgetSubmit+"\").click()");botonCloseModal.setAttribute("data-popbox-close","modal"+randomId);botonSubmit.addEventListener("click",function(e){var multi=!1;var newsletterWasSelected=!1;botonSubmit.removeAttribute("data-popbox-target");for(var i=0;i<form.elements.length;i++){if(form.elements[i].type!=="submit"){var name=form.elements[i].name;if(name==="newsletterCodeSelected"){multi=!0;if(form.elements[i].checked){newsletterWasSelected=!0;break}}}}
if(!multi||(multi&&newsletterWasSelected)){var randomElement=$("#"+randomId);if(!randomElement[0].checkValidity()){$("<input>",{type:"submit"}).hide().appendTo(randomElement).click().remove();botonSubmit.removeAttribute("data-popbox-target")}else{botonSubmit.setAttribute("data-popbox-target","modal"+randomId)}}});botonSubmit.setAttribute("data-popbox-target","modal"+randomId);botonSubmitChildren[0].setAttribute("type","button");botonSubmitChildren[0].setAttribute("value","Continuar");var widgetIdInput=document.createElement("input");widgetIdInput.type="hidden";widgetIdInput.name="widget_id";widgetIdInput.value=widgetId;form.appendChild(widgetIdInput);var privacyPolicyInput=document.createElement("input");privacyPolicyInput.type="hidden";privacyPolicyInput.name="privacyPolicy";privacyPolicyInput.value=prospectGigya.privacyPolicy;form.appendChild(privacyPolicyInput);var widgetSubmitInput=document.createElement("input");widgetSubmitInput.type="submit";widgetSubmitInput.name="widget_submit";widgetSubmitInput.value="widgetSubmitInput";widgetSubmitInput.id="widgetSubmit"+randomId;widgetSubmitInput.style.display="none";form.appendChild(widgetSubmitInput);var divLoader=document.createElement("div");divLoader.style.display="none";divLoader.style.position="relative";divLoader.className="loader";divLoader.innerHTML="<div class=\"prospect-title\">Apuntándote...<br/><img src=\"//cabeceras.vocento.com/comun/vocuser/v3/resources/images/ripple.gif\" alt=\"Prospect-loader\"></div>";form.parentNode.appendChild(divLoader);snippet.appendChild(widget)}else{if(env!=="PRO"){console.log("Invocation Errors Occured "+invocation.readyState+" and the status is "+invocation.status)}}}};invocation.send(null)}
function doSubscription(event){event.preventDefault();var errorSubscription=!1;var newsletterID=[];var invocation=new XMLHttpRequest();var url=urlProspectVoccore+"/vocuser/v1/prospect/user/newsletters/subscribe/email";var data=new FormData();var personalData={};var form=this;var widget_id=$(this).find("input[name='widget_id']").val();var nl_code=searchNlCode($(this).find("input[name='widget_id']").val());var multi=!1;var newsletterWasSelected=!1;var validFormElements=["widget_id","email","privacyPolicy","adsMedia","adsGroup","adsThirdparty","adsAll","adsGroupThirdparty"];var adsFormElements=["adsMedia","adsGroup","adsThirdparty","adsAll","adsGroupThirdparty"];for(var i=0;i<form.elements.length;i++){if(form.elements[i].type!=="submit"){var name=form.elements[i].name;var value=form.elements[i].value;if(-1!==validFormElements.indexOf(name)){if(-1!==adsFormElements.indexOf(name)){if(form.elements[i].checked){data[name]=!0;continue}else{data[name]=!1;continue}}
data[name]=value;continue}
if(name==="newsletterCodeSelected"){multi=!0;if(form.elements[i].checked){newsletterID.push(value);data.subscribeTo=newsletterID;newsletterWasSelected=!0}
continue}
personalData[name]=value}}
if(multi){url=urlProspectVoccore+"/vocuser/v1/prospect/user/newsletters/multi-subscribe"}
data.personalData=personalData;invocation.open("POST",url,!0);invocation.setRequestHeader("Content-Type","application/json");invocation.onreadystatechange=function(){if(invocation.readyState===XMLHttpRequest.DONE){var finalErrorCode=0;var tipologiaLogin="error";var uid="error";var newsletters=[];var div=document.createElement("div");var response=JSON.parse(invocation.responseText);if("undefined"===typeof response.result){finalErrorCode=response.errorCode}else{if(response.result.newsletters){newsletters=response.result.newsletters}else{newsletters=response.result}
for(var i=0;i<newsletters.length;i++){if(newsletters[i].errorCode){finalErrorCode=newsletters[i].errorCode}else{finalErrorCode=newsletters[i].nlSubscriptionCode}
div.innerHTML="<div class=\"widget-prospect-response\">"+newsletters[i].message+"</div>";if(response.result.newsletters){tipologiaLogin=response.result.userInfo.userType;uid=response.result.userInfo.UID}else{tipologiaLogin=response.result[i].userType;uid=response.result[i].UID}
if((finalErrorCode===200015)||(finalErrorCode===200001)){break}}}
if((finalErrorCode!==200015)&&(finalErrorCode!==200001)){errorSubscription=!0;div.innerHTML="<div class=\"widget-prospect-response\">Ha ocurrido un error, inténtalo más tarde</div>";if(finalErrorCode===200002){div.innerHTML="<div class=\"widget-prospect-response\">Ya estás registrado a esta Newsletter</div>"}
if(finalErrorCode===200004){div.innerHTML="<div class=\"widget-prospect-response\">Ya estás registrado a esta Newsletter</div>"}
var divButton=document.createElement("div");var button=document.createElement("input");button.type="submit";divButton.className="prospect-field prospect-submit";button.value="Volver";button.addEventListener("click",function(){goBackToWidget(div,form)});divButton.appendChild(button);div.appendChild(divButton);var triggerDataError={"auth":auth,"uid":uid,"nl_code":nl_code,"widget_id":widget_id,"tipologiaLogin":tipologiaLogin,"slot":slotList[widget_id],"tipoWidget":widgetTypeList[widget_id],"error":!0};mainEventListener.trigger("vocento.vocuser:prospect:trackSubscription",triggerDataError)}
var divPadre=form.parentNode;var nodes=divPadre.childNodes;for(var i=0;i<nodes.length;i++){if((hasClass(nodes[i],"loader")===!0)){nodes[i].style.display="none"}}
divPadre.appendChild(div);var triggerDataSuccess={"auth":auth,"uid":uid,"nl_code":nl_code,"widget_id":widget_id,"tipologiaLogin":tipologiaLogin,"slot":slotList[widget_id],"tipoWidget":widgetTypeList[widget_id],"error":!1};if(!errorSubscription){mainEventListener.trigger("vocento.vocuser:prospect:trackSubscription",triggerDataSuccess)}}}
form.style.display="none";var nodes=form.parentNode.childNodes;for(var i=0;i<nodes.length;i++){if((hasClass(nodes[i],"prospect-title")===!0)){nodes[i].style.display="none"}
if((hasClass(nodes[i],"prospect-description")===!0)){nodes[i].style.display="none"}
if((hasClass(nodes[i],"loader")===!0)){nodes[i].style.display="block"}}
invocation.send(JSON.stringify(data))}
function goBackToWidget(div,form){div.style.display="none";form.reset();form.style.display="block";var nodes=form.parentNode.childNodes;for(var i=0;i<nodes.length;i++){if((hasClass(nodes[i],"prospect-title")===!0)){nodes[i].style.display="block"}
if((hasClass(nodes[i],"prospect-description")===!0)){nodes[i].style.display="block"}}}
function hasClass(element,cls){return(" "+element.className+" ").indexOf(" "+cls+" ")>-1}
function searchNlCode(widget_id){var widgetListArray=widgetList.split(",");var nlCode="";widgetListArray.forEach(function(element){if(element.search(widget_id)!==-1){nlCode=element.substr(element.indexOf("-")+1,element.length)}});return nlCode}
function listTrackListener(xhr){currentRequests.push(xhr);xhr.addEventListener("readystatechange",function(){var idx;if(xhr.readyState===XMLHttpRequest.DONE){var json=JSON.parse(this.responseText);if(typeof json.result!=="undefined"){widgetList=json.result.widget_id+"-"+json.result.nl_code+","+widgetList}
idx=currentRequests.indexOf(this);if(idx>-1){currentRequests.splice(idx,1)}
if(currentRequests.length===0){widgetList=widgetList.substr(0,(widgetList.length-1));ajaxComplete.resolve(widgetList);Voonto.ready.then(function(){Voonto.require("popbox").then(function(Popbox){var popbox=new Popbox({blur:!0})})})}}},!1)}}(jQuery,Voonto))