(function(__wpcc){'use strict';__wpcc.e=__wpcc.e||{};__wpcc.e.scope={};__wpcc.e.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};__wpcc.e.arrayIterator=function(a){return{next:__wpcc.e.arrayIteratorImpl(a)}};__wpcc.e.ASSUME_ES5=!1;__wpcc.e.ASSUME_NO_NATIVE_MAP=!1;__wpcc.e.ASSUME_NO_NATIVE_SET=!1;__wpcc.e.SIMPLE_FROUND_POLYFILL=!1;
__wpcc.e.defineProperty=__wpcc.e.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};__wpcc.e.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};__wpcc.e.global=__wpcc.e.getGlobal(this);__wpcc.e.SYMBOL_PREFIX="jscomp_symbol_";
__wpcc.e.initSymbol=function(){__wpcc.e.initSymbol=function(){};__wpcc.e.global.Symbol||(__wpcc.e.global.Symbol=__wpcc.e.Symbol)};__wpcc.e.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;__wpcc.e.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};__wpcc.e.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
__wpcc.e.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new __wpcc.e.SymbolClass(__wpcc.e.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
__wpcc.e.initSymbolIterator=function(){__wpcc.e.initSymbol();var a=__wpcc.e.global.Symbol.iterator;a||(a=__wpcc.e.global.Symbol.iterator=__wpcc.e.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&__wpcc.e.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return __wpcc.e.iteratorPrototype(__wpcc.e.arrayIteratorImpl(this))}});__wpcc.e.initSymbolIterator=function(){}};
__wpcc.e.initSymbolAsyncIterator=function(){__wpcc.e.initSymbol();var a=__wpcc.e.global.Symbol.asyncIterator;a||(a=__wpcc.e.global.Symbol.asyncIterator=__wpcc.e.global.Symbol("Symbol.asyncIterator"));__wpcc.e.initSymbolAsyncIterator=function(){}};__wpcc.e.iteratorPrototype=function(a){__wpcc.e.initSymbolIterator();a={next:a};a[__wpcc.e.global.Symbol.iterator]=function(){return this};return a};__wpcc.e.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
__wpcc.e.assign="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var g in d)__wpcc.e.owns(d,g)&&(a[g]=d[g])}return a};__wpcc.e.polyfill=function(a,b){if(b){var c=__wpcc.e.global;a=a.split(".");for(var d=0;d<a.length-1;d++){var g=a[d];g in c||(c[g]={});c=c[g]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&__wpcc.e.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
__wpcc.e.polyfill("Object.assign",function(a){return a||__wpcc.e.assign},"es6","es3");__wpcc.e.iteratorFromArray=function(a,b){__wpcc.e.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
__wpcc.e.polyfill("Array.prototype.entries",function(a){return a?a:function(){return __wpcc.e.iteratorFromArray(this,function(a,c){return[a,c]})}},"es6","es3");__wpcc.e.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):__wpcc.e.arrayIterator(a)};__wpcc.e.FORCE_POLYFILL_PROMISE=!1;
__wpcc.e.polyfill("Promise",function(a){function b(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}}function c(){this.batch_=null}function d(a){return a instanceof b?a:new b(function(b){b(a)})}if(a&&!__wpcc.e.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};
var g=__wpcc.e.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){g(a,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(r){this.asyncThrow_(r)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};b.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=
!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};b.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};b.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};b.prototype.reject_=function(a){this.settle_(2,a)};b.prototype.fulfill_=function(a){this.settle_(1,a)};b.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new c;b.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};b.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(r){c.reject(r)}};b.prototype.then=function(a,c){function d(a,b){return"function"==typeof a?function(b){try{h(a(b))}catch(B){f(B)}}:b}var h,f,g=new b(function(a,b){h=a;f=b});this.callWhenSettled_(d(a,h),d(c,f));return g};
b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(c)};b.resolve=d;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,c){for(var h=__wpcc.e.makeIterator(a),l=h.next();!l.done;l=h.next())d(l.value).callWhenSettled_(b,
c)})};b.all=function(a){var c=__wpcc.e.makeIterator(a),h=c.next();return h.done?d([]):new b(function(a,b){function f(b){return function(c){l[b]=c;g--;0==g&&a(l)}}var l=[],g=0;do l.push(void 0),g++,d(h.value).callWhenSettled_(f(l.length-1),b),h=c.next();while(!h.done)})};return b},"es6","es3");__wpcc.e.polyfill("Object.entries",function(a){return a?a:function(a){var b=[],d;for(d in a)__wpcc.e.owns(a,d)&&b.push([d,a[d]]);return b}},"es8","es3");
__wpcc.e.polyfill("Array.prototype.keys",function(a){return a?a:function(){return __wpcc.e.iteratorFromArray(this,function(a){return a})}},"es6","es3");__wpcc.e.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
__wpcc.e.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var g=b.length;c=c||0;for(0>c&&(c=Math.max(c+g,0));c<g;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");
__wpcc.e.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};__wpcc.e.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==__wpcc.e.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");"undefined"===typeof __wpcc.k&&(__wpcc.k=function(){});
__wpcc.k.p="";}).call(this || window, (window.__wpcc = window.__wpcc || {}));

(function(__wpcc){/*
 JavaScript Cookie v2.2.1
 https://github.com/js-cookie/js-cookie

 Copyright 2006, 2015 Klaus Hartl & Fagner Brack
 Released under the MIT license
*/
'use strict';var m=function(){function a(){for(var a=0,b={};a<arguments.length;a++){var g=arguments[a],f;for(f in g)b[f]=g[f]}return b}function b(c){function d(){}function g(b,f,l){if("undefined"!==typeof document){l=a({path:"/"},d.defaults,l);"number"===typeof l.expires&&(l.expires=new Date(1*new Date+864E5*l.expires));l.expires=l.expires?l.expires.toUTCString():"";try{var h=JSON.stringify(f);/^[\{\[]/.test(h)&&(f=h)}catch(x){}f=c.write?c.write(f,b):encodeURIComponent(String(f)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,
decodeURIComponent);b=encodeURIComponent(String(b)).replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent).replace(/[\(\)]/g,escape);h="";for(var g in l)l[g]&&(h+="; "+g,!0!==l[g]&&(h+="="+l[g].split(";")[0]));return document.cookie=b+"="+f+h}}function f(a,b){if("undefined"!==typeof document){for(var d={},h=document.cookie?document.cookie.split("; "):[],f=0;f<h.length;f++){var g=h[f].split("="),q=g.slice(1).join("=");b||'"'!==q.charAt(0)||(q=q.slice(1,-1));try{var u=g[0].replace(/(%[0-9A-Z]{2})+/g,
decodeURIComponent);q=(c.read||c)(q,u)||q.replace(/(%[0-9A-Z]{2})+/g,decodeURIComponent);if(b)try{q=JSON.parse(q)}catch(D){}d[u]=q;if(a===u)break}catch(D){}}return a?d[a]:d}}d.set=g;d.get=function(a){return f(a,!1)};d.getJSON=function(a){return f(a,!0)};d.remove=function(b,c){g(b,"",a(c,{expires:-1}))};d.defaults={};d.withConverter=b;return d}return b(function(){})},aa=function(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,g=2562383102,
f=271733878,h=3285377520,q=[],l,r,y,x,J,u,D=Math.ceil((a.length/4+2)/16),B=[D],t=0;t<D;t++)for(B[t]=[],l=0;16>l;l++)B[t][l]=a.charCodeAt(64*t+4*l)<<24|a.charCodeAt(64*t+4*l+1)<<16|a.charCodeAt(64*t+4*l+2)<<8|a.charCodeAt(64*t+4*l+3);t=8*(a.length-1);a=D-1;B[a][14]=Math.floor(t/Math.pow(2,32));B[a][15]=t&4294967295;for(t=0;t<D;t++){for(a=0;16>a;a++)q[a]=B[t][a];for(a=16;80>a;a++)l=q[a-3]^q[a-8]^q[a-14]^q[a-16],q[a]=l<<1|l>>>31;l=c;r=d;y=g;x=f;J=h;for(a=0;80>a;a++){u=Math.floor(a/20);var ba=l<<5|l>>>
27;var ca=0==u?r&y^~r&x:1==u?r^y^x:2==u?r&y^r&x^y&x:r^y^x;u=ba+ca+J+b[u]+q[a]&4294967295;J=x;x=y;y=r<<30|r>>>2;r=l;l=u}c=c+l&4294967295;d=d+r&4294967295;g=g+y&4294967295;f=f+x&4294967295;h=h+J&4294967295}return[c,d,g,f,h]},da=function(){for(var a="",b=0;16>b;b++)a+=Math.random();return a},n=function(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a},p=function(a){"string"!==typeof a&&(a=String(a));if(/[^a-z0-9\-#$%&'*+.^_`|~]/i.test(a))throw new TypeError("Invalid character in header field name");
return a.toLowerCase()},v=function(a){"string"!==typeof a&&(a=String(a));return a},z=function(a){var b={next:function(){var b=a.shift();return{done:void 0===b,value:b}}};w.iterable&&(__wpcc.e.initSymbol(),__wpcc.e.initSymbolIterator(),b[Symbol.iterator]=function(){return b});return b},A=function(a){this.map={};a instanceof A?a.forEach(function(a,c){this.append(c,a)},this):Array.isArray(a)?a.forEach(function(a){this.append(a[0],a[1])},this):a&&Object.getOwnPropertyNames(a).forEach(function(b){this.append(b,
a[b])},this)},C=function(a){if(a.bodyUsed)return Promise.reject(new TypeError("Already read"));a.bodyUsed=!0},E=function(a){return new Promise(function(b,c){a.onload=function(){b(a.result)};a.onerror=function(){c(a.error)}})},ea=function(a){var b=new FileReader,c=E(b);b.readAsArrayBuffer(a);return c},fa=function(a){a=new Uint8Array(a);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=String.fromCharCode(a[c]);return b.join("")},F=function(a){if(a.slice)return a.slice(0);var b=new Uint8Array(a.byteLength);
b.set(new Uint8Array(a));return b.buffer},G=function(){this.bodyUsed=!1;this._initBody=function(a){(this._bodyInit=a)?"string"===typeof a?this._bodyText=a:w.blob&&Blob.prototype.isPrototypeOf(a)?this._bodyBlob=a:w.formData&&FormData.prototype.isPrototypeOf(a)?this._bodyFormData=a:w.searchParams&&URLSearchParams.prototype.isPrototypeOf(a)?this._bodyText=a.toString():w.arrayBuffer&&w.blob&&a&&DataView.prototype.isPrototypeOf(a)?(this._bodyArrayBuffer=F(a.buffer),this._bodyInit=new Blob([this._bodyArrayBuffer])):
w.arrayBuffer&&(ArrayBuffer.prototype.isPrototypeOf(a)||ha(a))?this._bodyArrayBuffer=F(a):this._bodyText=a=Object.prototype.toString.call(a):this._bodyText="";this.headers.get("content-type")||("string"===typeof a?this.headers.set("content-type","text/plain;charset=UTF-8"):this._bodyBlob&&this._bodyBlob.type?this.headers.set("content-type",this._bodyBlob.type):w.searchParams&&URLSearchParams.prototype.isPrototypeOf(a)&&this.headers.set("content-type","application/x-www-form-urlencoded;charset=UTF-8"))};
w.blob&&(this.blob=function(){var a=C(this);if(a)return a;if(this._bodyBlob)return Promise.resolve(this._bodyBlob);if(this._bodyArrayBuffer)return Promise.resolve(new Blob([this._bodyArrayBuffer]));if(this._bodyFormData)throw Error("could not read FormData body as blob");return Promise.resolve(new Blob([this._bodyText]))},this.arrayBuffer=function(){return this._bodyArrayBuffer?C(this)||Promise.resolve(this._bodyArrayBuffer):this.blob().then(ea)});this.text=function(){var a=C(this);if(a)return a;
if(this._bodyBlob){a=this._bodyBlob;var b=new FileReader,c=E(b);b.readAsText(a);return c}if(this._bodyArrayBuffer)return Promise.resolve(fa(this._bodyArrayBuffer));if(this._bodyFormData)throw Error("could not read FormData body as text");return Promise.resolve(this._bodyText)};w.formData&&(this.formData=function(){return this.text().then(ia)});this.json=function(){return this.text().then(JSON.parse)};return this},H=function(a,b){b=b||{};var c=b.body;if(a instanceof H){if(a.bodyUsed)throw new TypeError("Already read");
this.url=a.url;this.credentials=a.credentials;b.headers||(this.headers=new A(a.headers));this.method=a.method;this.mode=a.mode;this.signal=a.signal;c||null==a._bodyInit||(c=a._bodyInit,a.bodyUsed=!0)}else this.url=String(a);this.credentials=b.credentials||this.credentials||"same-origin";if(b.headers||!this.headers)this.headers=new A(b.headers);a=b.method||this.method||"GET";var d=a.toUpperCase();this.method=-1<ja.indexOf(d)?d:a;this.mode=b.mode||this.mode||null;this.signal=b.signal||this.signal;this.referrer=
null;if(("GET"===this.method||"HEAD"===this.method)&&c)throw new TypeError("Body not allowed for GET or HEAD requests");this._initBody(c)},ia=function(a){var b=new FormData;a.trim().split("&").forEach(function(a){if(a){var c=a.split("=");a=c.shift().replace(/\+/g," ");c=c.join("=").replace(/\+/g," ");b.append(decodeURIComponent(a),decodeURIComponent(c))}});return b},ka=function(a){var b=new A;a.replace(/\r?\n[\t ]+/g," ").split(/\r?\n/).forEach(function(a){var c=a.split(":");if(a=c.shift().trim())c=
c.join(":").trim(),b.append(a,c)});return b},I=function(a,b){b||(b={});this.type="default";this.status=void 0===b.status?200:b.status;this.ok=200<=this.status&&300>this.status;this.statusText="statusText"in b?b.statusText:"OK";this.headers=new A(b.headers);this.url=b.url||"";this._initBody(a)},L=function(a,b){return new Promise(function(c,d){function g(){h.abort()}var f=new H(a,b);if(f.signal&&f.signal.aborted)return d(new K("Aborted","AbortError"));var h=new XMLHttpRequest;h.onload=function(){var a=
{status:h.status,statusText:h.statusText,headers:ka(h.getAllResponseHeaders()||"")};a.url="responseURL"in h?h.responseURL:a.headers.get("X-Request-URL");c(new I("response"in h?h.response:h.responseText,a))};h.onerror=function(){d(new TypeError("Network request failed"))};h.ontimeout=function(){d(new TypeError("Network request failed"))};h.onabort=function(){d(new K("Aborted","AbortError"))};h.open(f.method,f.url,!0);"include"===f.credentials?h.withCredentials=!0:"omit"===f.credentials&&(h.withCredentials=
!1);"responseType"in h&&w.blob&&(h.responseType="blob");f.headers.forEach(function(a,b){h.setRequestHeader(b,a)});f.signal&&(f.signal.addEventListener("abort",g),h.onreadystatechange=function(){4===h.readyState&&f.signal.removeEventListener("abort",g)});h.send("undefined"===typeof f._bodyInit?null:f._bodyInit)})},M=function(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a},N=function(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,
configurable:!0,writable:!0}):a[b]=c;return a},P=function(a,b){b=b||{};if(Object.keys(O).includes(a))O[a](b);else console.warn('"'+a+'" is  not a valid Chartbeat event.')},Q={},R;!(R="function"===typeof m?m.call(Q,__wpcc.k,Q,{}):m,void 0!==R&&(Q=R));Q=m();var S={};Object.defineProperty(S,"__esModule",{value:!0});S.VERSION=4;S.PING_URL="//ping.chartbeat.net/ping/milkyway";S.COOKIE_NAMES={ORIGINAL:"_cb",SUBSCRIPTIONS:"_cbs"};S.CALL_TYPES={PAYWALL_SHOWN:"ps",CONVERSION:"c",CUSTOM_TYPE:"ct"};S.CONFIG_NAME="_sf_async_config";S.BASE_PING_KEYS={HOST:"h",PATH:"p",UUID_USER:"u",UUID_SESSION:"t",DOMAIN:"d"};S.PING_KEYS={TYPE:"_st",LAST_PAYWALL_PATH:"_spp",LAST_PAYWALL_DOMAIN:"_spd",VERSION:"_sV",TIMESTAMP:"_sd",CUSTOM_TYPE:"_sct"};
S.COOKIE_KEYS={LAST_PAYWALL_PATH:"p",LAST_PAYWALL_DOMAIN:"d",U_KEY:"u"};var T={};Object.defineProperty(T,"__esModule",{value:!0});T.createEntropyString=T.generateUKey=T.getDomainWithoutSubdomain=T.getDomain=T.getPath=T.getHost=T.getDomainOrDefault=T.setDomainOnConfig=T.getConfig=void 0;var la=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a},U=T.getConfig=function(){return window[S.CONFIG_NAME]};
T.setDomainOnConfig=function(a){window[S.CONFIG_NAME]=la({},window[S.CONFIG_NAME],{domain:a})};var ma=T.getDomainOrDefault=function(a){var b=U();return b&&b.domain?b.domain:a};T.getHost=function(){return ma(na(window.location.hostname))};T.getPath=function(){var a=U();a=a&&a.path?a.path:window.location.pathname;return oa()+a};
var oa=T.getDomain=function(){return ma(window.location.hostname)},na=T.getDomainWithoutSubdomain=function(){for(var a=0,b=document.domain,c=b.split("."),d="_gd"+(new Date).getTime();a<c.length-1&&-1==document.cookie.indexOf(d+"="+d);)b=c.slice(-1-++a).join("."),document.cookie=d+"="+d+";domain="+b+";";document.cookie=d+"=;expires=Thu, 01 Jan 1970 00:00:01 GMT;domain="+b+";";return b};
T.generateUKey=function(a,b){var c="";a=aa(encodeURIComponent(a));a.splice(b||5,a.length);a.forEach(function(a){var b=c;if(0==a)a="A";else{a>>>=0;for(var d="",h;0<a;)h=a%64,d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(h)+d,a>>>=6;a=d}c=b+a});return c};
T.createEntropyString=function(a,b){var c=window.navigator,d=window.screen;d=[c.userAgent,c.platform,(new Date).getTimezoneOffset(),d.width+d.height+d.colorDepth];for(var g=0;g<c.plugins.length;g++){var f=c.plugins[g];d.push(f.name+f.description+f.filename+f[0].type)}!1===a&&(a=window.performance,d=d.concat([a&&a.now?a.now():"",document.title,window.location.href,(new Date).getTime(),da()]));return d.concat(b||[]).join()};var V={};Object.defineProperty(V,"__esModule",{value:!0});V.getLastPaywallDomain=V.getLastPaywallPath=V.getUKey=V.getSubscriptionsCookie=V.setSubscriptionsCookie=V.checkSubscriptionsCookieExists=void 0;var W=Q&&Q.__esModule?Q:{default:Q};V.checkSubscriptionsCookieExists=function(){return W.default.get(S.COOKIE_NAMES.SUBSCRIPTIONS)?!0:!1};
V.setSubscriptionsCookie=function(a){var b,c=pa(),d=(0,T.getPath)(),g=(0,T.getDomainWithoutSubdomain)(),f=(0,T.getDomainOrDefault)();d=(b={},n(b,S.COOKIE_KEYS.U_KEY,c),n(b,S.COOKIE_KEYS.LAST_PAYWALL_PATH,d),n(b,S.COOKIE_KEYS.LAST_PAYWALL_DOMAIN,f),b);a&&(d[S.COOKIE_KEYS.LAST_PAYWALL_PATH]=a);W.default.set(S.COOKIE_NAMES.SUBSCRIPTIONS,d,{domain:"."+g,expires:1/48});W.default.set(S.COOKIE_NAMES.ORIGINAL,c,{domain:"."+g,expires:1/48})};
var X=V.getSubscriptionsCookie=function(){return W.default.getJSON(S.COOKIE_NAMES.SUBSCRIPTIONS)},pa=V.getUKey=function(){var a=X();if(a&&a.u)return a.u;a=W.default.get(S.COOKIE_NAMES.ORIGINAL);return a||(0,T.generateUKey)((0,T.createEntropyString)(!1),3)};V.getLastPaywallPath=function(){var a=X();return a&&a.p};V.getLastPaywallDomain=function(){var a=X();return a&&a.d};__wpcc.e.initSymbol();var qa="Symbol"in self&&"iterator"in Symbol,Y;if(Y="FileReader"in self&&"Blob"in self)try{new Blob,Y=!0}catch(a){Y=!1}var w={searchParams:"URLSearchParams"in self,iterable:qa,blob:Y,formData:"FormData"in self,arrayBuffer:"ArrayBuffer"in self};
if(w.arrayBuffer)var ra="[object Int8Array];[object Uint8Array];[object Uint8ClampedArray];[object Int16Array];[object Uint16Array];[object Int32Array];[object Uint32Array];[object Float32Array];[object Float64Array]".split(";"),ha=ArrayBuffer.isView||function(a){return a&&-1<ra.indexOf(Object.prototype.toString.call(a))};A.prototype.append=function(a,b){a=p(a);b=v(b);var c=this.map[a];this.map[a]=c?c+", "+b:b};A.prototype["delete"]=function(a){delete this.map[p(a)]};
A.prototype.get=function(a){a=p(a);return this.has(a)?this.map[a]:null};A.prototype.has=function(a){return this.map.hasOwnProperty(p(a))};A.prototype.set=function(a,b){this.map[p(a)]=v(b)};A.prototype.forEach=function(a,b){for(var c in this.map)this.map.hasOwnProperty(c)&&a.call(b,this.map[c],c,this)};A.prototype.keys=function(){var a=[];this.forEach(function(b,c){a.push(c)});return z(a)};A.prototype.values=function(){var a=[];this.forEach(function(b){a.push(b)});return z(a)};
A.prototype.entries=function(){var a=[];this.forEach(function(b,c){a.push([c,b])});return z(a)};w.iterable&&(__wpcc.e.initSymbol(),__wpcc.e.initSymbolIterator(),A.prototype[Symbol.iterator]=A.prototype.entries);var ja="DELETE GET HEAD OPTIONS POST PUT".split(" ");H.prototype.clone=function(){return new H(this,{body:this._bodyInit})};G.call(H.prototype);G.call(I.prototype);
I.prototype.clone=function(){return new I(this._bodyInit,{status:this.status,statusText:this.statusText,headers:new A(this.headers),url:this.url})};I.error=function(){var a=new I(null,{status:0,statusText:""});a.type="error";return a};var sa=[301,302,303,307,308];I.redirect=function(a,b){if(-1===sa.indexOf(b))throw new RangeError("Invalid status code");return new I(null,{status:b,headers:{location:a}})};var K=self.DOMException;
try{new K}catch(a){K=function(b,c){this.message=b;this.name=c;this.stack=Error(b).stack},K.prototype=Object.create(Error.prototype),K.prototype.constructor=K}L.polyfill=!0;self.fetch||(self.fetch=L,self.Headers=A,self.Request=H,self.Response=I);var Z={};Object.defineProperty(Z,"__esModule",{value:!0});Z.ping=void 0;var ta=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};
Z.ping=function(a){var b,c=Math.round((new Date).getTime()/1E3),d=(0,V.getUKey)(),g=(0,T.getHost)(),f=(0,T.getDomainOrDefault)();a=ta({},a,(b={},M(b,S.BASE_PING_KEYS.HOST,g),M(b,S.BASE_PING_KEYS.DOMAIN,f),M(b,S.BASE_PING_KEYS.UUID_USER,d),M(b,S.PING_KEYS.VERSION,S.VERSION),M(b,S.PING_KEYS.TIMESTAMP,c),b));b="?"+Object.entries(a).map(function(a){if(!Array.isArray(a))if(Symbol.iterator in Object(a)){var b=[],c=!0,d=!1,f=void 0;try{for(var g=a[Symbol.iterator](),h;!(c=(h=g.next()).done)&&(b.push(h.value),
2!==b.length);c=!0);}catch(u){d=!0,f=u}finally{try{if(!c&&g["return"])g["return"]()}finally{if(d)throw f;}}a=b}else throw new TypeError("Invalid attempt to destructure non-iterable instance");return a[0]+"="+encodeURIComponent(a[1])}).join("&");fetch(""+S.PING_URL+b,{mode:"no-cors"}).then(function(){console.info("Milkyway ping fired.")}).catch(function(a){console.error("Milkyway Ping Request Error "+a)})};var O={trackConversion:function(a){var b;a=a.pathOverride||null;var c=(0,T.getPath)(),d=(0,V.getLastPaywallPath)(),g=(0,V.getLastPaywallDomain)();c=(b={},N(b,S.BASE_PING_KEYS.PATH,c),N(b,S.PING_KEYS.LAST_PAYWALL_PATH,d),N(b,S.PING_KEYS.LAST_PAYWALL_DOMAIN,g),N(b,S.PING_KEYS.TYPE,S.CALL_TYPES.CONVERSION),b);a&&(c[S.BASE_PING_KEYS.PATH]=a);(0,Z.ping)(c)},trackPaywallShown:function(a){var b;a=a.pathOverride||null;(0,V.setSubscriptionsCookie)(a);var c=(0,T.getPath)();c=(b={},N(b,S.BASE_PING_KEYS.PATH,
c),N(b,S.PING_KEYS.TYPE,S.CALL_TYPES.PAYWALL_SHOWN),b);a&&(c[S.BASE_PING_KEYS.PATH]=a);(0,Z.ping)(c)},trackCustomSubscriptionsEvent:function(a){var b,c=a.customEventType;a=a.pathOverride||null;if(c){var d=(0,V.getLastPaywallPath)(),g=(0,V.getLastPaywallDomain)(),f=(0,T.getPath)();c=(b={},N(b,S.BASE_PING_KEYS.PATH,f),N(b,S.PING_KEYS.LAST_PAYWALL_PATH,d),N(b,S.PING_KEYS.LAST_PAYWALL_DOMAIN,g),N(b,S.PING_KEYS.TYPE,S.CALL_TYPES.CUSTOM_TYPE),N(b,S.PING_KEYS.CUSTOM_TYPE,c),b);a&&(c[S.BASE_PING_KEYS.PATH]=
a);(0,Z.ping)(c)}else console.warn("customEventType is required in options for custom events.")},setDomain:function(a){(a=a.domainValue)?(0,T.setDomainOnConfig)(a):console.warn("setDomain requires a domainValue to be provided in options to be set.")}};(function(){var a=window.chartbeat.q;a&&a.length&&a.forEach(function(a){P(a[0],a[1])});window.chartbeat=P})();}).call(this || window, (window.__wpcc = window.__wpcc || {}));

//# sourceMappingURL=milkyway.js.map