(function tagManagerProspectManager($){var tgmModulosRotacion="";var tgmTipologiaLogin="";var tgmIDGigya="";var tgmProceso="";var tgmSlot="";var tgmCustomerService="";var tgmFunnel="";var tgmProcesoFinalizado="si";var tgmErroresFormulario="";var tgmSeccion="";var env="";var eventData={widgetList:'',tagManagerMode:'',ajaxComplete:''};var mainEventListener=$('body');mainEventListener.on("vocento.vocuser:prospect:trackSubscription",function(event,dataObject){trackSubscription(dataObject.auth,dataObject.uid,dataObject.nl_code,dataObject.widget_id,dataObject.tipologiaLogin,dataObject.slot,dataObject.tipoWidget,dataObject.error)});function prepareConfirmEmailTrack(widget_id,nl_code,user_id,error){resetVars();tgmIDGigya="prospect-"+user_id;tgmProceso=widget_id+"_"+nl_code;tgmSeccion=TagManager.get().seccion;tgmTipologiaLogin="prospect";tgmFunnel="exito-suscripcion-nl-usuario-prospect-validado";if(error){tgmIDGigya='';tgmFunnel='';setearErrores('Error:'+widget_id+"_"+nl_code+"-no-validado-generico")}}
function prepareUnsubscribeTrack(nl_code,user_id,unsubscribeReason,tipologiaLogin,error,validNlId){resetVars();tgmSeccion='confirmacion-baja-prospect';tgmTipologiaLogin=tipologiaLogin;switch(tgmTipologiaLogin){case 'prospect':tgmIDGigya='prospect-'+user_id;tgmFunnel='prospectbaja-'+unsubscribeReason+'-'+nl_code;break;case 'registrado':tgmIDGigya=user_id;tgmCustomerService='600';tgmFunnel='gigyabaja-'+unsubscribeReason+'-'+nl_code;break;case 'anonimo':tgmIDGigya='';break}
tgmProceso='baja-prospect';if(error){var errorMessage;if(validNlId){errorMessage='-ko-baja-nl-usuario-no-existe'}else{errorMessage='-ko-baja-nl-newsletter-no-existe'}
setearErrores('Error:'+nl_code+errorMessage)}}
function prepareWidgetSubscriptionTrack(nl_code,user_id,widget_id,tipologiaLogin,slot,error,funnel){resetVars();tgmIDGigya=user_id;tgmSeccion=TagManager.get().seccion;tgmTipologiaLogin=tipologiaLogin;tgmProceso=widget_id+"_"+nl_code;tgmSlot=slot;tgmCustomerService='600';tgmModulosRotacion=eventData.widgetList;tgmFunnel=funnel;if((''===TagManager.get().IDGigya)&&('registrado'!==tipologiaLogin)){tgmCustomerService=''}
if('registrado'===tipologiaLogin){tipologiaLogin='gigya-logado'}
if(error){setearErrores('Error:'+widget_id+"-"+nl_code+"-ya-suscrito-nl-"+tipologiaLogin)}}
function prepareWidgetListTrack(widgetList){resetVars();tgmModulosRotacion=widgetList;tgmSeccion=TagManager.get().seccion;tgmIDGigya=TagManager.get().IDGigya;tgmProcesoFinalizado='';tgmTipologiaLogin='PR';if(''===tgmIDGigya){tgmTipologiaLogin='anonimo'}else{tgmTipologiaLogin='registrado';tgmCustomerService='600'}}
function trackSubscription(auth,user_id,nl_code,widget_id,tipologiaLogin,slot,tipoWidget,error){if(auth){prepareWidgetSubscriptionTrack(nl_code,TagManager.get().IDGigya,widget_id,'registrado',slot,error,"exito-suscripcion-nl-gigya-logado")}else{switch(tipologiaLogin){case 'PR':prepareWidgetSubscriptionTrack(nl_code,'prospect-'+user_id,widget_id,'prospect',slot,error,'exito-suscripcion-nl-usuario-prospect');break;case 'GG':prepareWidgetSubscriptionTrack(nl_code,'',widget_id,'gigya-no-logado',slot,error,'exito-suscripcion-nl-gigya-no-logado');break;default:prepareWidgetSubscriptionTrack(nl_code,user_id,widget_id,'prospect',slot,error,'exito-suscripcion-nl-usuario-prospect');break}}
sendTrack();if(env!=='pro'){console.log("Envío el track de suscripción"+error);console.log(TagManager.get())}}
function sendTrack(){TagManager.set({modulosRotacion:tgmModulosRotacion,tipologiaLogin:tgmTipologiaLogin,IDGigya:tgmIDGigya,proceso:tgmProceso,slot:tgmSlot,customerService:tgmCustomerService,funnel:tgmFunnel,procesoFinalizado:tgmProcesoFinalizado,erroresFormulario:tgmErroresFormulario,seccion:tgmSeccion,tipoContenido:'widget'});TagManager.track('prospect')}
function setearErrores(error){if(""===tgmErroresFormulario){tgmErroresFormulario=error;tgmProcesoFinalizado="si";tgmFunnel=""}}
function resetVars(){tgmModulosRotacion="";tgmTipologiaLogin="";tgmIDGigya="";tgmProceso="";tgmSlot="";tgmCustomerService="";tgmFunnel="";tgmProcesoFinalizado="si";tgmErroresFormulario="";tgmSeccion=""}
function initCurrentEnv(){var result='pro';if(/^des/.test(window.location.host)||/^integracion/.test(window.location.host)||/^areapersonal-des/.test(window.location.host)||/^areapersonalm-des/.test(window.location.host)||/^docker/.test(window.location.host)){result='des'}
if(/^pre/.test(window.location.host)||/^areapersonal-pre/.test(window.location.host)||/^areapersonalm-pre/.test(window.location.host)){result='pre'}
if(/^pro/.test(window.location.host)||/^secure/.test(window.location.host)||/^new/.test(window.location.host)||/^www/.test(window.location.host)){result='pro'}
if(/^local/.test(window.location.host)||/^userplayground-miguelromero2000/.test(window.location.host)||/^desnlocal/.test(window.location.host)||/^deshared/.test(window.location.host)||/^desn-user/.test(window.location.host)||/^des-vocuser/.test(window.location.host)){result='local'}
return result}
$(document).ready(function(){if(('undefined'!==typeof TagManager)&&(TagManager)){env=initCurrentEnv();TagManager.ready.then(function(){mainEventListener.trigger("vocento.vocuser:prospect:getTagManagerMode",[eventData]);mainEventListener.trigger("vocento.vocuser:prospect:getAjaxComplete",[eventData]);switch(eventData.tagManagerMode){case 'confirmSubscription':var error=!1;if(1===confirmSubscriptionError){error=!0}
prepareConfirmEmailTrack(widget_id,nl_code,user_id,error);sendTrack();if(env!=='pro'){console.log("Envío el track de confirmación");console.log(TagManager.get())}
break;case 'unsubscribe':var error=!1;if(1!==unsubscribeSuccess){error=!0}
prepareUnsubscribeTrack(nl_code,user_id,unsubscribeReason,tipologiaLogin,error,!0);sendTrack();if(env!=='pro'){console.log("Envío el track de baja");console.log(TagManager.get())}
break;case 'unsubscribeValidNlId':if(0===validNlId){prepareUnsubscribeTrack('','','','anonimo',!0,!1);sendTrack();if(env!=='pro'){console.log("Envío el track de error de ValidNlId");console.log(TagManager.get())}}
break;case 'widget':$.when(eventData.ajaxComplete).then(function(){mainEventListener.trigger("vocento.vocuser:prospect:getWidgetList",[eventData]);prepareWidgetListTrack(eventData.widgetList);sendTrack();if(env!=='pro'){console.log("Envío el track de lista");console.log(TagManager.get())}})
break}})}})}(window.jQuery))